name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -C 3_Implementation/src
    - name: clean
      run: make -C 3_Implentation/ clean
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck

