# Name of the project
PROJECT_NAME = DomesticElectricityBill

# Output directory
BUILD = build


#TargetName : Dependencies
#<TAB>commands


Build : ElectricityBill.c calculator.c
	gcc ElectricityBill.c  -o ElectricityBill.out

Run : Build
	./ElectricityBill.out